# Файл сборки BochKraft: Canary (порт Lithium). Как на сервере — выключены три группы миксинов,
# которые конфликтуют с Valkyrien Skies (POI, пересечения коллизий) и с LittleTiles / загрузкой чанков.
mixin.ai.poi=false
mixin.entity.collisions.intersection=false
mixin.world.chunk_tickets=false
